# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import food_classification_pb2 as food__classification__pb2


class FoodAiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckGpuStatus = channel.unary_unary(
                '/FoodAi/CheckGpuStatus',
                request_serializer=food__classification__pb2.Empty.SerializeToString,
                response_deserializer=food__classification__pb2.GpuStatus.FromString,
                )
        self.PredictFoodImage = channel.unary_unary(
                '/FoodAi/PredictFoodImage',
                request_serializer=food__classification__pb2.FoodImage.SerializeToString,
                response_deserializer=food__classification__pb2.PredictionResult.FromString,
                )


class FoodAiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckGpuStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictFoodImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FoodAiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckGpuStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckGpuStatus,
                    request_deserializer=food__classification__pb2.Empty.FromString,
                    response_serializer=food__classification__pb2.GpuStatus.SerializeToString,
            ),
            'PredictFoodImage': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictFoodImage,
                    request_deserializer=food__classification__pb2.FoodImage.FromString,
                    response_serializer=food__classification__pb2.PredictionResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FoodAi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FoodAi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckGpuStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FoodAi/CheckGpuStatus',
            food__classification__pb2.Empty.SerializeToString,
            food__classification__pb2.GpuStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PredictFoodImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FoodAi/PredictFoodImage',
            food__classification__pb2.FoodImage.SerializeToString,
            food__classification__pb2.PredictionResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
